apiVersion: v1
kind: ConfigMap
metadata:
  name: my-set-config
data:
  run.sh: |
    #!/bin/sh
    Sleep 10 # wait for vars to set

    echo "Starting initializing for pod primary"

    cp /mnt/scripts/my.cnf /mnt/data/my.cnf
    cp /mnt/scripts/init-mysql.sql /mnt/data/b-init-mysql-cluster.sql
    cp /mnt/scripts/init-test-script.sql /mnt/data/a-init-test-script.sql
    cp /mnt/scripts/prep-work.sh /mnt/data/prep-work.sh
    touch /mnt/data/auto.cnf       
  my.cnf: |
    # For advice on how to change settings please see
    # http://dev.mysql.com/doc/refman/5.7/en/server-configuration-defaults.html

    [mysqld]
    #
    # Remove leading # and set to the amount of RAM for the most important data
    # cache in MySQL. Start at 70% of total RAM for dedicated server, else 10%.
    # innodb_buffer_pool_size = 128M
    #
    # Remove leading # to turn on a very important data integrity option: logging
    # changes to the binary log between backups.
    # log_bin
    #
    # Remove leading # to set options mainly useful for reporting servers.
    # The server defaults are faster for transactions and fast SELECTs.
    # Adjust sizes as needed, experiment to find the optimal values.
    # join_buffer_size = 128M
    # sort_buffer_size = 2M
    # read_rnd_buffer_size = 2M
    skip-host-cache
    skip-name-resolve
    datadir=/var/lib/mysql
    socket=/var/run/mysqld/mysqld.sock
    secure-file-priv=/var/lib/mysql-files
    user=mysql

    # Replica
    bind-address = 0.0.0.0
    server-id = 1
    log_bin = binlog
    binlog_do_db = db

    # Disabling symbolic-links is recommended to prevent assorted security risks
    symbolic-links=0

    log-error=/var/log/mysqld.log
    pid-file=/var/run/mysqld/mysqld.pid
    #[client]
    #socket=/var/run/mysqld/mysqld.sock

    !includedir /etc/mysql/conf.d/

