apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql-replica
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
    nodePort: 30306
      #name: mysql-port
  selector:
    app: mysql-replica
    tier: mysql

